### ISSUE TITLE
How can I define new themes?

### ISSUE THREAD

**Issue by marcosrosse** [gaheldev/kitty-gnome-lightdark-mode-switcher#3]
Hi 👋🏾 ,

How can I define other themes config?

I would like to use this repository themes configs, but changing it in `set-kitty-mode`  did not loaded the themes.

**Comment by marcosrosse** [comment]
I found out. Thank you!

**Comment by gaheldev** [comment]
Hi :)
I should probably make it configurable, I just never had the need for it. If you feel like doing it don't hesitate to open a PR!
